### ISSUE TITLE
Projects merge

### ISSUE THREAD

**Issue by telesvar** [puyuan/py-nanoid#6]
Hello! I also recreated [new version](https://github.com/aidarkhanov/py-nanoid) of Nano ID on Python and would like to know, whether it is possible to merge our projects now as I see you are being active on updating the project too.

Why do I want this?
py-nanoid is hosted on PyPi with the name of nanoid. In order not to create confusion among users, it is better to have more powerful single package without duplicates on pip, such as nanoid2 (which is allegedly has been taken myself) and other nonsense.

Would love to hear from you good news!

**Comment by puyuan** [comment]
Yes,  I am a bit behind following all the latest changes in nanoid 2. I am in progress of resolving #4  to keep the library updated.

I am happy to have coauthors, contributors in this project. Since this package was already discussed with the original author's approval and linked to the official site, maybe it makes sense to fork and create a PR for your new changes into this project?  I have made similar changes in v2.0, so you can review those to correct my current implementation. 

I think 2 things that can be improved.

1. Verify the correctness of the generation logic. There is alot of details in the random function generators that could potentially go wrong. If your implementation has better algorithm, style,  and performance, it can definitely improve the current one. 
2. Add test cases that actually checks correctness. Right now, I am just checking the size of the ids and whether exceptions will be generated for a certain amount of ids. 

I agree with you we should keep just one pip package, i.e nanoid, and just update the package version. I think the original author intends to update the versions progressively. He did not specifically mention version 1 or 2 would be completely incompatible, rather newer version will improve upon the older.  It kind of makes sense to not add the version in the package name and just update the package version. 

Feel free to discuss more

**Comment by telesvar** [comment]
Definitely looking at ai's nanoid API progression, he was clearly careful at keeping backwards compatibility.

As for algorithm efficiency, I have benchmarked mine implementation and compared with yours and the difference was minimal (see included pic). Our algorithms pass unit tests which are transferred from original repo. That said, basic features such as support of international chars, etc. just work.

![image](https://user-images.githubusercontent.com/36963426/48315123-81fa8b80-e5fc-11e8-8248-33b348b1affa.png)
_`generate1()` is mine, `generate2()` is yours and `fast_generate()` is [simply using random function](https://github.com/aidarkhanov/py-nanoid/blob/master/nanoid/non_secure_generate.py#L11), but that turns out not that fast._

**Comment by telesvar** [comment]
I will look into projects integration as well.
Nevertheless, Nano ID dictionary package [was ported](https://github.com/aidarkhanov/nanoid-dictionary) to python, that is, my personal suggestion is full integration with my recreation would be a lot easier as I kept the same API and created tests as you did.

What do you think about it?

**Comment by puyuan** [comment]
1. Your benchmarks and test cases are all good to incorporate. I currently haven't mentioned anything about performance vs uuid, secure vs non-secure in the README because I don't have numbers to back it up. Maybe after we incorporate this we can give some comments in the README. Here is also some reference. https://eli.thegreenplace.net/2018/slow-and-fast-methods-for-generating-random-integers-in-python/

2. NanoID dictionary is a good tool. I see you currently incorporate it as a dependency in your main package. However, I see it as an independent tool, like the [js](https://github.com/CyberAP/nanoid-dictionary) version, which is not a dependency for js nanoid. Maybe we shouldn't add it as a dependency to the main package(we can mention in README), just to keep this simple package simple,   what do you think? 

3. I am not sure how you want to do full-integration?  At least interface-wise,  nanoid.generate shouldn't change. This was the published python official package, and should remain backward compatible. Maybe you can create a PR to this repo, and I can get some ideas how you want to do the integration.

**Comment by telesvar** [comment]
Yeah, definitely you are right that Nano ID has to be library independent and stand out as a completely standalone tool. This point is to be mirrored in a today's pull-request.

I saw the article and want to try out faster random functions, thanks for pointing this out.

Update: I ran the benchmark once again and `randint(0, alphabet_len - 1)` was about 4x slower on Python 3 than `alphabet_len * random()`, which is so far the fastest variant.
